# -*- coding: utf-8 -*-
"""Task1_Human Survey

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13aA8jwf57BN4BaKklsJxKnGlvTypKZgi
"""

import numpy as np

survey_results = {
    "Random_Baseline": [1, 1, 2, 1, 1, 1, 2, 3, 1, 1],
    "Markov_Chain": [2, 3, 2, 1, 4, 2, 3, 1, 3, 2],
    "Task1_LSTM": [4, 3, 2, 5, 3, 4, 2, 3, 2, 4]
}

# Calculating the final Human Score for table
print("=== HUMAN SURVEY FINAL SCORES ===")
for model_name, scores in survey_results.items():
    avg_score = np.mean(scores)
    print(f"{model_name}: {avg_score:.2f} / 5.0")